/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.user;

import br.com.biblioteca.main.BlibiotecaMain;
import br.com.biblioteca.bd.Conexao;
import br.com.biblioteca.livros.CadastroLivros;
import br.com.biblioteca.livros.ListagemLivros;
import br.com.bliblioteca.valida.Valida;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author IFMS
 */
public class CadastroUsuario extends javax.swing.JFrame {

    private Connection conn;
    Usuario u = new Usuario();
    
    
    public CadastroUsuario() {
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        btnAlterar.setEnabled(false);
        btnCadastar.setEnabled(true);
        btnExcluir.setEnabled(false);
        txtNome.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        CbPerfil = new javax.swing.JComboBox<>();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCadastar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Perfil");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        CbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Blibiotecario" }));

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Tela Inicial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCadastar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastar.setText("CADASTRAR");
        btnCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnConsultar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCadastar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnConsultar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCadastar))
                .addGap(5, 5, 5)
                .addComponent(jButton1))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CADASTRO DE USUÁRIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastarActionPerformed
        Valida v = new Valida();
       Integer resp = v.validaNome(txtNome.getText());
       if(resp != 0){
           
           conn = Conexao.conecta();
        
        try {
            if(conn == null || conn.isClosed()){
                JOptionPane.showMessageDialog(null,"erro ao conectar ao banco de dados!");
                System.exit(-1);
            }
            
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Date aux = Date.from(Instant.now());
                String nome = "'"+txtNome.getText()+"'";
                String perfil = ",'"+getCbPerfil().getSelectedItem().toString()+"'";
                String dataCad = ",'"+sdf.format(aux)+"'";

                String sql = "INSERT INTO tbUsuario (nome, perfil, data_cad) VALUES "
                        + "("+nome+perfil+dataCad+")";
                //JOptionPane.showMessageDialog(null,"sql: "+sql);

                Statement stmt = conn.createStatement();
                
                Integer retorno = stmt.executeUpdate(sql);
                
                if(retorno != 0){
                    JOptionPane.showMessageDialog(null,"Usuário cadastrado com sucesso!","CADASTRO",JOptionPane.INFORMATION_MESSAGE);
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Não foi possivel cadastar!","CADASTRO",JOptionPane.ERROR_MESSAGE);
                }
                
                
                
                stmt.close();
                conn.close();
                
                listagemUser();
                
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
           
       }
      
 
    }//GEN-LAST:event_btnCadastarActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
             Valida v = new Valida();
       Integer resp = v.validaNome(txtNome.getText());
       if(resp != 0){
        
           conn = Conexao.conecta();
        
            try {
                if(conn == null || conn.isClosed()){
                    JOptionPane.showMessageDialog(null,"erro ao conectar ao banco de dados!");
                    System.exit(-1);
                }


                    String nome = "'"+txtNome.getText()+"'";    
                    String perfil = "'"+getCbPerfil().getSelectedItem().toString()+"'";


                    String sql = "UPDATE  tbUsuario SET nome = "+ nome +", perfil = "+ perfil + " WHERE  idtbUsuario = " + u.getId();
                    //JOptionPane.showMessageDialog(null,"sql: "+sql);

                    Statement stmt = conn.createStatement();

                    Integer retorno = stmt.executeUpdate(sql);

                        if(retorno != 0){
                            JOptionPane.showMessageDialog(null,"Usuario "+ nome +" Atualizado com sucesso!","CADASTRO",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null,"Não foi possivel Atualizar!","CADASTRO",JOptionPane.ERROR_MESSAGE);
                        }

                    stmt.close();
                    conn.close();
                    
                    listagemUser();
                
            } catch (SQLException ex) {
                Logger.getLogger(CadastroLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            ListagemUsuarios lu = new ListagemUsuarios();
            lu.setVisible(true);
            setVisible(false);
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String nome = "'"+txtNome.getText()+"'"; 
        
        int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir o usuário " + nome + "?");
        
        if(resp == JOptionPane.YES_OPTION){
        
            conn = Conexao.conecta();
        
            try {
                if(conn == null || conn.isClosed()){
                    JOptionPane.showMessageDialog(null,"erro ao conectar ao banco de dados!");
                    System.exit(-1);
                }


                       
                    


                    String sql = "DELETE FROM  tbUsuario  WHERE  idtbUsuario = " + u.getId();
                    //JOptionPane.showMessageDialog(null,"sql: "+sql);

                    Statement stmt = conn.createStatement();

                    Integer retorno = stmt.executeUpdate(sql);

                        if(retorno != 0){
                            JOptionPane.showMessageDialog(null,"Usuario "+ nome +" excluido com sucesso!","CADASTRO",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null,"Não foi possivel excluir!","CADASTRO",JOptionPane.ERROR_MESSAGE);
                        }

                    stmt.close();
                    conn.close();
                    
                    listagemUser();
                
            } catch (SQLException ex) {
                Logger.getLogger(CadastroLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            BlibiotecaMain bm = new BlibiotecaMain();
        bm.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbPerfil;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<String> getCbPerfil() {
        return CbPerfil;
    }

    public void setCbPerfil(javax.swing.JComboBox<String> CbPerfil) {
        this.CbPerfil = CbPerfil;
    }
    
    void setDados(String  id){
    btnCadastar.setEnabled(false);
    btnAlterar.setEnabled(true);
    btnExcluir.setEnabled(true);
    conn = Conexao.conecta();
    
    try {
            if(conn == null || conn.isClosed()){
                JOptionPane.showMessageDialog(null,"Erro ao conectar ao banco de dados!");
                System.exit(-1);
            }
                Integer cond = Integer.parseInt(id);

                String sql = "SELECT idtbUsuario, nome, perfil, data_cad from tbUsuario where idtbUsuario = '" + cond + "'";
        
        try ( 
                Statement stmt = conn.createStatement()) {
                //select
                ResultSet res = stmt.executeQuery(sql);
            
                    while(res.next()){
                        
                    
                    u.setId(res.getInt("idtbUsuario"));
                    u.setPerfil(res.getString("perfil"));
                    
                    txtNome.setText(res.getString("nome"));
                    CbPerfil.getModel().setSelectedItem(u.getPerfil());

                    
                }
                stmt.close();
            }
        
                conn.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(ListagemLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    
    private void listagemUser(){
        try {
            ListagemUsuarios lu = new ListagemUsuarios();
            lu.setVisible(true);
            setVisible(false);
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

}
