-- MySQL Script generated by MySQL Workbench
-- Fri Jun 29 20:48:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`tbUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tbUsuario` (
  `idtbUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`idtbUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tbLivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tbLivro` (
  `idtbLivro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`idtbLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tbLocalizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tbLocalizacao` (
  `idtbLocalizacao` INT NOT NULL AUTO_INCREMENT,
  `estante` VARCHAR(45) NULL,
  `prateleira` VARCHAR(45) NULL,
  `coluna` VARCHAR(45) NULL,
  PRIMARY KEY (`idtbLocalizacao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
