/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.localizacao;

import br.com.biblioteca.main.BlibiotecaMain;
import br.com.biblioteca.bd.Conexao;
import br.com.biblioteca.livros.CadastroLivros;
import br.com.biblioteca.livros.ListagemLivros;
import br.com.bliblioteca.valida.Valida;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author IFMS
 */
public class CadastroLocalizacao extends javax.swing.JFrame {

    private Connection conn;
    Localizacao l = new Localizacao();
    
    
    public CadastroLocalizacao() {
        initComponents();
        
        setLocationRelativeTo(null);
        btnAlterar.setEnabled(false);
        btnCadastar.setEnabled(true);
        btnExcluir.setEnabled(false);
        txtEstante.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEstante = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCadastar = new javax.swing.JButton();
        txtColuna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrateleira = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ESTANTE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PRATELEIRA");

        txtEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstanteActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Tela Inicial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCadastar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastar.setText("CADASTRAR");
        btnCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastarActionPerformed(evt);
            }
        });

        txtColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColunaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("COLUNA");

        txtPrateleira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrateleiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addGap(6, 6, 6)
                                .addComponent(btnCadastar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstante, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrateleira, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtColuna, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnConsultar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCadastar))
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addGap(4, 4, 4))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CADASTRO DE LOCALIZAÇÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstanteActionPerformed

    private void btnCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastarActionPerformed
        Valida v = new Valida();
       Integer resp = v.validaLocalizacao(txtEstante.getText()+txtPrateleira.getText()+txtColuna.getText());
       if(resp != 0){
           
           conn = Conexao.conecta();
        
        try {
            if(conn == null || conn.isClosed()){
                JOptionPane.showMessageDialog(null,"erro ao conectar ao banco de dados!");
                System.exit(-1);
            }
            
                
                String estante = "'"+txtEstante.getText()+"'";
                String prateleira = ",'"+txtPrateleira.getText()+"'";
                String coluna = ",'"+txtColuna.getText()+"'";
                

                String sql = "INSERT INTO tbLocalizacao (estante, prateleira, coluna) VALUES "
                        + "("+estante+prateleira+coluna+")";
                //JOptionPane.showMessageDialog(null,"sql: "+sql);

                Statement stmt = conn.createStatement();
                
                Integer retorno = stmt.executeUpdate(sql);
                
                if(retorno != 0){
                    JOptionPane.showMessageDialog(null,"Localização cadastrada com sucesso!","CADASTRO",JOptionPane.INFORMATION_MESSAGE);
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Não foi possivel cadastar!","CADASTRO",JOptionPane.ERROR_MESSAGE);
                }
                
                
                
                stmt.close();
                conn.close();
                
                listagemUser();
                
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLocalizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
           
       }
      
 
    }//GEN-LAST:event_btnCadastarActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
             Valida v = new Valida();
       Integer resp = v.validaLocalizacao(txtEstante.getText()+txtPrateleira.getText()+txtColuna.getText());
 
       if(resp != 0){
        
           conn = Conexao.conecta();
        
            try {
                if(conn == null || conn.isClosed()){
                    JOptionPane.showMessageDialog(null,"erro ao conectar ao banco de dados!");
                    System.exit(-1);
                }


                    String estante = "'"+txtEstante.getText()+"'";
                    String prateleira = "'"+txtPrateleira.getText()+"'";
                    String coluna = "'"+txtColuna.getText()+"'";


                    String sql = "UPDATE  tbLocalizacao SET estante = "+ estante +", prateleira = "+ prateleira +""
                            + ", coluna = "+ coluna + " WHERE  idtbLocalizacao = " + l.getId();
                    //JOptionPane.showMessageDialog(null,"sql: "+sql);

                    Statement stmt = conn.createStatement();

                    Integer retorno = stmt.executeUpdate(sql);

                        if(retorno != 0){
                            JOptionPane.showMessageDialog(null,"localização  atualizada com sucesso!","CADASTRO",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null,"Não foi possivel Atualizar!","CADASTRO",JOptionPane.ERROR_MESSAGE);
                        }

                    stmt.close();
                    conn.close();
                    
                    listagemUser();
                
            } catch (SQLException ex) {
                Logger.getLogger(CadastroLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            ListagemLocalizacao lu = new ListagemLocalizacao();
            lu.setVisible(true);
            setVisible(false);
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroLocalizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        
        int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir a localização  ?");
        
        if(resp == JOptionPane.YES_OPTION){
        
            conn = Conexao.conecta();
        
            try {
                if(conn == null || conn.isClosed()){
                    JOptionPane.showMessageDialog(null,"erro ao conectar ao banco de dados!");
                    System.exit(-1);
                }


                       
                    


                    String sql = "DELETE FROM  tbLocalizacao  WHERE  idtbLocalizacao = " + l.getId();
                    //JOptionPane.showMessageDialog(null,"sql: "+sql);

                    Statement stmt = conn.createStatement();

                    Integer retorno = stmt.executeUpdate(sql);

                        if(retorno != 0){
                            JOptionPane.showMessageDialog(null,"localização excluida com sucesso!","CADASTRO",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null,"Não foi possivel excluir!","CADASTRO",JOptionPane.ERROR_MESSAGE);
                        }

                    stmt.close();
                    conn.close();
                    
                    listagemUser();
                
            } catch (SQLException ex) {
                Logger.getLogger(CadastroLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            BlibiotecaMain bm = new BlibiotecaMain();
        bm.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColunaActionPerformed

    private void txtPrateleiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrateleiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrateleiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLocalizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtColuna;
    private javax.swing.JTextField txtEstante;
    private javax.swing.JTextField txtPrateleira;
    // End of variables declaration//GEN-END:variables

    
    
    void setDados(String  id){
    btnCadastar.setEnabled(false);
    btnAlterar.setEnabled(true);
    btnExcluir.setEnabled(true);
    conn = Conexao.conecta();
    
    try {
            if(conn == null || conn.isClosed()){
                JOptionPane.showMessageDialog(null,"Erro ao conectar ao banco de dados!");
                System.exit(-1);
            }
                Integer cond = Integer.parseInt(id);

                String sql = "SELECT idtbLocalizacao, estante, prateleira, coluna from tbLocalizacao where idtbLocalizacao = '" + cond + "'";
        
        try ( 
                Statement stmt = conn.createStatement()) {
                //select
                ResultSet res = stmt.executeQuery(sql);
            
                    while(res.next()){
                        
                    
                    l.setId(res.getInt("idtbLocalizacao"));
                    
                    txtEstante.setText(res.getString("estante"));
                    txtPrateleira.setText(res.getString("prateleira"));
                    txtColuna.setText(res.getString("coluna"));
                    
                    

                    
                }
                stmt.close();
            }
        
                conn.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(ListagemLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    
    private void listagemUser(){
        try {
            ListagemLocalizacao lu = new ListagemLocalizacao();
            lu.setVisible(true);
            setVisible(false);
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroLocalizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public javax.swing.JTextField getTxtColuna() {
        return txtColuna;
    }

    public void setTxtColuna(javax.swing.JTextField txtColuna) {
        this.txtColuna = txtColuna;
    }

    public javax.swing.JTextField getTxtEstante() {
        return txtEstante;
    }

    public void setTxtEstante(javax.swing.JTextField txtEstante) {
        this.txtEstante = txtEstante;
    }

    public javax.swing.JTextField getTxtPrateleira() {
        return txtPrateleira;
    }

    public void setTxtPrateleira(javax.swing.JTextField txtPrateleira) {
        this.txtPrateleira = txtPrateleira;
    }
   

}
